### ISSUE TITLE
Incorrect Links and Broken URL in README

### ISSUE THREAD

**Issue by fartzy** [promotedai/openmetrics#7]
Just FYI, there are links in the README file that point to Google Docs which are not publicly accessible. This prevents users from being able to view the linked content. Below are the problematic links and their corresponding issues:

 - [System Overview - Presentation](https://drive.google.com/file/d/19mwOiuxUji-T_Zxqcr4J2NDgZXHypmd6/view?usp=sharing)
 - [Metrics Solution](https://drive.google.com/file/d/1IqrMIY-S8hcsOp7bUnTAHhUgBy1SaJre/view?usp=sharing)
 - [Detailed Diagrams/Metrics](https://drive.google.com/file/d/1TI9C0e-2B9qwLQDlyQqRuclLRxzko611/view?usp=sharing)
 
 Additionally, the link [src/main/java/ai/promoted/metrics/logprocessor/stream/](https://github.com/promotedai/openmetrics/blob/main/pipeline/src/main/java/ai/promoted/metrics/logprocessor/stream/README.md) results in a 404 error.
 
 These issues hinder users from accessing important documentation and source code. It would be greatly appreciated if the necessary corrections can be made to ensure that the links are accessible to the public and the broken URL is fixed.

**Comment by danbosnichill** [comment]
Thanks for the issue.  ETA probably ~3 months.  We have a major revision to the repo in private and probably won't update openmetrics until it's in a stable state.

**Comment by danbosnichill** [comment]
I fixed the first 3 links.  The `/stream/` link will be fixed the next time we fork our private repos over to public.
